apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-db
  namespace: expense
spec:
  replicas: 1
  selector: { matchLabels: { app: expense-db } }
  template:
    metadata: { labels: { app: expense-db } }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: postgres
          image: postgres:15
          ports: [{ containerPort: 5432 }]
          env:
            - { name: POSTGRES_DB, value: expense }
            - { name: POSTGRES_USER, value: expense }
            - { name: POSTGRES_PASSWORD, value: expense123 }
            - { name: PGDATA, value: /var/lib/postgresql/data/pgdata }
          readinessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            seccompProfile: { type: RuntimeDefault }
          volumeMounts:
            - { name: pgdata, mountPath: /var/lib/postgresql/data }
      volumes:
        - name: pgdata
          persistentVolumeClaim: { claimName: pvc-expense-postgres }
---
apiVersion: v1
kind: Service
metadata:
  name: expense-db
  namespace: expense
spec:
  selector: { app: expense-db }
  ports:
    - port: 5432
      targetPort: 5432
