apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-expense-postgres
spec:
  capacity: { storage: 5Gi }
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: /var/lib/microshift/pv/pgdata-new }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-expense-postgres
  namespace: expense
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 5Gi } }
  volumeName: pv-expense-postgres
