apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-app
  namespace: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-app
  template:
    metadata:
      labels:
        app: expense-app
    spec:
      containers:
        - name: app
          image: docker.io/mdsajidali/expense-tracker:1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DJANGO_SECRET_KEY
              value: change-me
            - name: DJANGO_DEBUG
              value: "False"
            - name: DJANGO_ALLOWED_HOSTS
              value: "*,54.89.159.32,localhost,127.0.0.1"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: expense-app
  namespace: expense
spec:
  type: NodePort
  selector:
    app: expense-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080

