apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: pgdata, namespace: expense }
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: postgres, namespace: expense }
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
      - name: postgres
        image: postgres:15
        envFrom: [{ secretRef: { name: db-secret } }]
        ports: [{ containerPort: 5432, name: pg } ]
        volumeMounts: [{ name: data, mountPath: /var/lib/postgresql/data }]
      volumes:
      - name: data
        persistentVolumeClaim: { claimName: pgdata }
---
apiVersion: v1
kind: Service
metadata: { name: postgres, namespace: expense }
spec:
  selector: { app: postgres }
  ports: [{ port: 5432, targetPort: 5432 }]
