version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: expensedb
      POSTGRES_USER: expense
      POSTGRES_PASSWORD: expensepass
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      placement: { constraints: [node.role == manager] }

  web:
    image: <dockerhub-username>/expense-tracker:1.0
    environment:
      DEBUG: "False"
      SECRET_KEY: prod-secret-change-me
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      DB_NAME: expensedb
      DB_USER: expense
      DB_PASSWORD: expensepass
      DB_HOST: db
      DB_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on: [db]
    deploy:
      replicas: 2
      restart_policy: { condition: on-failure }

volumes:
  pgdata:

