apiVersion: 1
deleteDatasources:
  - name: Prometheus
    type: prometheus

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://127.0.0.1:9090
    isDefault: true
    editable: true
