apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      hostNetwork: true
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.49.1
          ports:
            - containerPort: 8080
              hostPort: 8080  # Ensure this port is exposed correctly
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: varrun
              mountPath: /var/run
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker
              readOnly: true
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: varrun
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /var/lib/docker
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup

