apiVersion: v1
kind: Service
metadata:
  name: prometheus-node
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 32290

