global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (host metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.74.128:9100']

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.74.128:8080']

  # Blackbox exporter (HTTP uptime for all orchestrators)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://192.168.74.128:8000  # Expense Tracker app on Mesos
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: http://192.168.74.128:8000
      - target_label: __address__
        replacement: 192.168.74.128:9115

  # Mesos Master
  - job_name: 'mesos_master'
    metrics_path: /metrics/snapshot
    static_configs:
      - targets: ['192.168.74.128:5050']

  # Mesos Agent
  - job_name: 'mesos_agent'
    metrics_path: /metrics/snapshot
    static_configs:
      - targets: ['192.168.74.128:5051']

  # Marathon (using updated port 8088)
  - job_name: 'marathon'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.74.128:8088']

