global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']  # for local compose on Mac/Win
        labels: { app: 'expense-web' }
