version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-expensedb}
      POSTGRES_USER: ${DB_USER:-expense}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-expensepass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: .env
    environment:
      CREATE_SUPERUSER: "1"
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: adminpass
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  pgdata:
